
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jan 10 17:16:44 CET 2025
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAP = 18;
  public static final int LBRACKET = 43;
  public static final int MULT = 23;
  public static final int CHAR = 49;
  public static final int CONST = 20;
  public static final int EQUALS = 26;
  public static final int NOTEQUAL = 27;
  public static final int LPAREN = 41;
  public static final int SEMI = 37;
  public static final int GREATER = 28;
  public static final int CONTINUE = 13;
  public static final int INTERFACE = 19;
  public static final int LESS = 30;
  public static final int MINUS = 22;
  public static final int RPAREN = 42;
  public static final int AND = 32;
  public static final int OR = 33;
  public static final int BOOL = 48;
  public static final int COMMA = 39;
  public static final int CLASS = 4;
  public static final int INC = 35;
  public static final int DIV = 24;
  public static final int PLUS = 21;
  public static final int LESSEQ = 31;
  public static final int ASSIGN = 34;
  public static final int IF = 6;
  public static final int DOT = 40;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int RBRACKET = 44;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int NUMBER = 47;
  public static final int MOD = 25;
  public static final int IDENT = 50;
  public static final int BREAK = 3;
  public static final int VOID = 11;
  public static final int COLON = 38;
  public static final int UNION = 15;
  public static final int LBRACE = 45;
  public static final int ELSE = 5;
  public static final int READ = 9;
  public static final int WHILE = 17;
  public static final int RBRACE = 46;
  public static final int EXTENDS = 12;
  public static final int GREATEREQ = 29;
  public static final int DEC = 36;
  public static final int PRINT = 8;
  public static final int DO = 16;
  public static final int SET = 14;
}

